---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: tets
  label: test
- type: heading
  label: Pages
- type: document
  path: content/home.md
  label: Home
- type: document
  path: content/wat-we-oplossen.md
  label: Wat we oplossen
- type: document
  path: content/onze-aanpak.md
  label: Onze aanpak
- type: document
  path: content/contact.md
  label: Contact
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
